variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  TERM: "dumb"

before_script:
  - chmod +x gradlew

stages:
  - test

java-11:
  stage: test
  image: eclipse-temurin:11
  script: ./gradlew clean build dist copyExe

java-17:
  stage: test
  image: eclipse-temurin:17
  script: ./gradlew clean build dist copyExe
