variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  TERM: "dumb"

before_script:
  - chmod +x gradlew

stages:
  - test

java-8:
  stage: test
  image: openjdk:8
  script: ./gradlew clean build dist

java-11:
  stage: test
  image: openjdk:11
  script: ./gradlew clean build dist

java-latest:
  stage: test
  image: openjdk:latest
  script: java -version && ./gradlew clean build dist
