language: java
sudo: false
dist: trusty

# don't build on tag push
if: tag IS blank

git:
  depth: false

before_install:
  - chmod +x gradlew

# override install to skip 'gradle assemble'
install: true

env:
  global:
    - TERM=dumb
    - JADX_LAST_TAG=$(git describe --abbrev=0 --tags)
    - JADX_VERSION="${JADX_LAST_TAG:1}-b$TRAVIS_BUILD_NUMBER-$(git rev-parse --short HEAD)"

jdk:
  - openjdk8
  - oraclejdk8
  - openjdk11

script: ./gradlew clean build

jobs:
  include:
    - stage: deploy-unstable
      jdk: openjdk8
      if: branch = master AND env(BINTRAY_KEY) IS present
      script: bash scripts/travis-master.sh

    - stage: deploy-release
      jdk: openjdk8
      if: branch = release AND env(GH_TOKEN) IS present
      script: bash scripts/travis-release.sh
