language: java
jdk:
    - oraclejdk8

env:
    - TERM=dumb GRADLE_OPTS="-Dorg.gradle.daemon=false"

before_install:
    - chmod +x gradlew

script:
    - sed -i " 1 s/.*/&-b$TRAVIS_BUILD_NUMBER-$(git rev-parse --short HEAD)/" version
    - cat version
    - sed -i "s/BUILD_VERSION/$(head -c -1 version)/g" bintray.json
    - ./gradlew clean build

after_success:
    - ./gradlew clean build jacocoTestReport
    - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
    - ./gradlew clean sonarqube -Dsonar.host.url=$SONAR_HOST -Dsonar.organization=$SONAR_ORG -Dsonar.login=$SONAR_TOKEN
    - ./gradlew clean dist

deploy:
    provider: bintray
    edge:
      branch: v1.8.47
    file: bintray.json
    user: skylot
    key: $BINTRAY_KEY
    skip_cleanup: true
    on:
      branch: master
      tags: false

sudo: false

notifications:
    email:
        - skylot@gmail.com
